apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: audiobookshelf
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: audiobookshelf
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: audiobookshelf
    spec:
      nodeName: debianman
      # dnsPolicy: "None"
      # dnsConfig:
      #   nameservers:
      #     - 1.1.1.1
      containers:
      #   - args:
      #       - tunnel
      #       - --no-autoupdate
      #       - --protocol
      #       - http2
      #       - run
      #       - --token
      #       - $(TUNNEL_TOKEN)
      #     env:
      #       - name: TUNNEL_TOKEN
      #         valueFrom:
      #           secretKeyRef:
      #             name: audiobookshelf-app
      #             key: cf_tunnel_token
      #     image: docker.io/cloudflare/cloudflared:2025.11.1
      #     name: cloudflare-tunnel
        - env:
            - name: TZ
              value: Europe/Berlin
          image: ghcr.io/advplyr/audiobookshelf:2.32.1 
          name: audiobookshelf
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /audiobooks
              name: audiobooks
            - mountPath: /podcasts
              name: podcasts
            - mountPath: /config
              name: config
            - mountPath: /metadata
              name: metadata
      restartPolicy: Always
      volumes:
        - name: audiobooks
          hostPath:
            path: /mnt/qnap/audiobookshelf/audiobooks
            type: Directory
        - name: podcasts
          hostPath:
            path: /mnt/qnap/audiobookshelf/podcasts
            type: Directory
        - name: config
          hostPath:
            path: /mnt/qnap/audiobookshelf/config
            type: Directory
        - name: metadata
          hostPath:
            path: /mnt/qnap/audiobookshelf/metadata
            type: Directory
