services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.31.0
    ports:
      - 13379:80
    volumes:
      - ${AUDIOBOOK_FOLDER_PATH}:/audiobooks
      - ${PODCASTS_FOLDER_PATH}:/podcasts
      - ${CONFIG_FOLDER_PATH}:/config
      - ${METADATA_FOLDER_PATH}:/metadata
    environment:
      - TZ=Europe/Berlin

  tunnel:
    image: docker.io/cloudflare/cloudflared:2025.11.1
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
