---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: teamspeak
  name: teamspeak
  namespace: teamspeak
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: teamspeak
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: teamspeak
    spec:
      containers:
        - env:
            - name: TS3SERVER_DB_PLUGIN
              value: ts3db_postgresql
            - name: TS3SERVER_DB_SQLCREATEPATH
              value: create_postgresql
            - name: TS3SERVER_DB_WAITUNTILREADY
              value: "30"
            - name: TS3SERVER_LICENSE
              value: accept
          envFrom:
          - secretRef:
              name: db-secret
          image: teamspeak:3.13.7
          name: teamspeak
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - ps -ef | grep ts3server | grep -v grep
            initialDelaySeconds: 10
            periodSeconds: 30
          ports:
            - containerPort: 9987
              protocol: UDP
            - containerPort: 10011
          resources: {}
      restartPolicy: Always
