---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: teamspeak
  name: teamspeak
  namespace: teamspeak
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: teamspeak
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: teamspeak
    spec:
      nodeName: whisperforge
      containers:
        - env:
            # reference: https://github.com/teamspeak/teamspeak6-server/blob/main/CONFIG.md
            - name: TSSERVER_LICENSE_ACCEPTED
              value: accept
          image: teamspeaksystems/teamspeak6-server:v6.0.0-beta8
          name: teamspeak-server
          ports:
            - containerPort: 9987
              protocol: UDP
            - containerPort: 30033
              protocol: TCP
            - containerPort: 10080
              protocol: TCP
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 1000m
          volumeMounts:
            - mountPath: /var/tsserver
              name: teamspeak-data
      restartPolicy: Always
      volumes:
        - name: teamspeak-data
          hostPath:
            path: /opt/teamspeak6
            type: DirectoryOrCreate
