apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: teamspeak-prometheus
  name: teamspeak-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: teamspeak-prometheus
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: teamspeak-prometheus
    spec:
      containers:
        - env:
            - name: TEAMSPEAK_HOST
              value: teamspeak.teamspeak.svc.cluster.local
            - name: TEAMSPEAK_PASSWORD
              value: ""
          image: teamspeak-prometheus:latest
          name: teamspeak-prometheus
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
